# Generated by Django 3.2.4 on 2021-07-13 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('domains', '0001_initial'), ('domains', '0002_domain_receive_type'), ('domains', '0003_auto_20180707_1658'), ('domains', '0004_auto_20181023_1931'), ('domains', '0005_auto_20181103_1106')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('destination', models.CharField(blank=True, max_length=128, null=True, verbose_name='Destination')),
                ('relay_type', models.CharField(default='smtp', max_length=64, verbose_name='Relay type')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='Last updated on')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('catchall', models.BooleanField(default=False, verbose_name='Catchall')),
                ('allowed_accounts', models.IntegerField(default=-1, verbose_name='Allowed user accounts for domain')),
                ('receive_type', models.CharField(choices=[('load_balanced', 'Load balancing'), ('failover', 'Failover')], default='failover', max_length=25, verbose_name='Recieve type')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ('-name',),
            },
        ),
    ]
