# Generated by Django 2.0.7 on 2018-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='receive_type',
            field=models.CharField(choices=[('load_balanced', 'Load balancing'), ('failover', 'Failover')], default='failover', max_length=12),
        ),
    ]
