# Generated by Django 2.0 on 2018-02-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='relay_destination',
        ),
        migrations.AlterField(
            model_name='domain',
            name='destination',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
