# Generated by Django 2.0.7 on 2018-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_receive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='receive_type',
            field=models.CharField(choices=[('load_balanced', 'Load balancing'), ('failover', 'Failover')], default='failover', max_length=25),
        ),
    ]
