# Generated by Django 2.0 on 2018-02-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0002_auto_20180204_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_domain_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='catchall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailuser',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
        migrations.AddField(
            model_name='mailuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
