# Generated by Django 2.1.2 on 2018-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20180707_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='allowed_accounts',
            field=models.IntegerField(default=-1, verbose_name='Allowed user accounts for domain'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='catchall',
            field=models.BooleanField(default=False, verbose_name='Catchall'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='destination',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='receive_type',
            field=models.CharField(choices=[('load_balanced', 'Load balancing'), ('failover', 'Failover')], default='failover', max_length=25, verbose_name='Recieve type'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='relay_type',
            field=models.CharField(default='smtp', max_length=64, verbose_name='Relay type'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated on'),
        ),
    ]
