# Generated by Django 2.0 on 2018-02-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20180207_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain',
            new_name='name',
        ),
    ]
