# Generated by Django 2.1.3 on 2018-11-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20181023_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('-name',), 'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
    ]
