# Generated by Django 2.0 on 2018-02-07 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20180207_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
