# Generated by Django 2.0 on 2018-02-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_auto_20180207_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailuser',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='domains.Domain'),
        ),
    ]
