# Generated by Django 2.0.3 on 2018-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20180207_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailuser',
            name='email',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailuser',
            name='full_email',
            field=models.CharField(default='default', max_length=511),
            preserve_default=False,
        ),
    ]
