# Generated by Django 2.0.3 on 2018-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_auto_20180405_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
