# Generated by Django 2.0 on 2017-12-21 20:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(max_length=255)),
                ('from_domain', models.CharField(max_length=64)),
                ('to_address', models.CharField(max_length=255)),
                ('to_domain', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('client_ip', models.GenericIPAddressField()),
                ('mailscanner_hostname', models.CharField(max_length=255)),
                ('spam_score', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('token', models.CharField(max_length=255)),
                ('whitelisted', models.BooleanField()),
                ('blacklisted', models.BooleanField()),
                ('is_spam', models.BooleanField()),
                ('is_rbl_listed', models.BooleanField()),
                ('quarantined', models.BooleanField()),
                ('infected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageHeaders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
        migrations.CreateModel(
            name='RblReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
        migrations.CreateModel(
            name='McpReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
    ]
