# Generated by Django 3.2.4 on 2021-07-13 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('mail', '0001_initial'), ('mail', '0002_auto_20180709_1543'), ('mail', '0003_delete_spamassassinruledescription'), ('mail', '0004_smtprelay'), ('mail', '0005_smtprelay_active'), ('mail', '0006_smtprelay_hostname'), ('mail', '0007_auto_20180716_2132'), ('mail', '0008_auto_20181023_1931'), ('mail', '0009_auto_20181106_1909'), ('mail', '0010_auto_20181227_1957'), ('mail', '0011_message_scanned'), ('mail', '0012_auto_20190102_1758'), ('mail', '0013_auto_20200808_1930')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailscannerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='McpReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='From')),
                ('from_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('to_address', models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='To')),
                ('to_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subject', models.TextField(blank=True, db_index=True, default='')),
                ('client_ip', models.GenericIPAddressField(db_index=True, null=True, verbose_name='Client IP')),
                ('mailscanner_hostname', models.CharField(db_index=True, max_length=255)),
                ('spam_score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=7)),
                ('mcp_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('size', models.FloatField(default=0)),
                ('token', models.CharField(max_length=255, null=True)),
                ('mailq_id', models.TextField(null=True, verbose_name='Mailqueue identification')),
                ('whitelisted', models.BooleanField(db_index=True, default=False)),
                ('blacklisted', models.BooleanField(db_index=True, default=False)),
                ('is_spam', models.BooleanField(db_index=True, default=False)),
                ('is_mcp', models.BooleanField(db_index=True, default=False)),
                ('is_rbl_listed', models.BooleanField(db_index=True, default=False, verbose_name='Is RBL listed')),
                ('quarantined', models.BooleanField(db_index=True, default=False)),
                ('infected', models.BooleanField(db_index=True, default=False)),
                ('released', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('-timestamp',),
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='RblReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='SpamAssassinRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='TransportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('transport_host', models.CharField(db_index=True, max_length=255)),
                ('transport_type', models.CharField(db_index=True, max_length=255)),
                ('relay_host', models.CharField(db_index=True, max_length=255)),
                ('dsn', models.CharField(db_index=True, max_length=255)),
                ('dsn_message', models.TextField(db_index=True)),
                ('delay', models.DurationField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.message')),
            ],
            options={
                'ordering': ('timestamp',),
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'from_domain'], name='mail_messag_from_ad_73cd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'to_domain'], name='mail_messag_to_addr_0cd3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'to_address'], name='mail_messag_from_ad_f1acb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'to_domain'], name='mail_messag_from_ad_5833fe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'from_domain'], name='mail_messag_to_addr_06c9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'mailscanner_hostname'], name='mail_messag_client__f7ba93_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'blacklisted'], name='mail_messag_from_ad_676957_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'whitelisted'], name='mail_messag_from_ad_238390_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'infected'], name='mail_messag_from_ad_1f0d67_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'is_spam'], name='mail_messag_from_ad_12e43e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'quarantined'], name='mail_messag_from_ad_2d4929_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'is_rbl_listed'], name='mail_messag_from_ad_2b9f87_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'blacklisted'], name='mail_messag_to_addr_eec52d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'whitelisted'], name='mail_messag_to_addr_0f2921_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'infected'], name='mail_messag_to_addr_a7125d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'is_spam'], name='mail_messag_to_addr_5cae52_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'quarantined'], name='mail_messag_to_addr_11d06f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'is_rbl_listed'], name='mail_messag_to_addr_1e8598_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'blacklisted'], name='mail_messag_from_do_bf466c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'whitelisted'], name='mail_messag_from_do_be122b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'infected'], name='mail_messag_from_do_4a62bf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'is_spam'], name='mail_messag_from_do_3d2668_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'quarantined'], name='mail_messag_from_do_e2e93e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'is_rbl_listed'], name='mail_messag_from_do_d8e7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'blacklisted'], name='mail_messag_to_doma_48b624_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'whitelisted'], name='mail_messag_to_doma_da63ed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'infected'], name='mail_messag_to_doma_e640e6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'is_spam'], name='mail_messag_to_doma_752e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'quarantined'], name='mail_messag_to_doma_1647b6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'is_rbl_listed'], name='mail_messag_to_doma_729d90_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'blacklisted'], name='mail_messag_client__31eae6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'whitelisted'], name='mail_messag_client__9d8977_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'infected'], name='mail_messag_client__1577f4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'is_spam'], name='mail_messag_client__ef32e1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'quarantined'], name='mail_messag_client__0c4c11_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'is_rbl_listed'], name='mail_messag_client__961a40_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'blacklisted'], name='mail_messag_mailsca_eec5db_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'whitelisted'], name='mail_messag_mailsca_e7750e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'infected'], name='mail_messag_mailsca_9bc8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'is_spam'], name='mail_messag_mailsca_04192b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'quarantined'], name='mail_messag_mailsca_75aba8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'is_rbl_listed'], name='mail_messag_mailsca_7437e6_idx'),
        ),
        migrations.AddField(
            model_name='mcpreport',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.message'),
        ),
        migrations.AddField(
            model_name='mailscannerreport',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.message'),
        ),
        migrations.AddField(
            model_name='headers',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.message'),
        ),
        migrations.RenameModel(
            old_name='SpamAssassinRule',
            new_name='SpamAssassinRuleDescription',
        ),
        migrations.DeleteModel(
            name='SpamAssassinRuleDescription',
        ),
        migrations.AlterModelOptions(
            name='headers',
            options={'verbose_name': 'headers', 'verbose_name_plural': 'headers'},
        ),
        migrations.AlterModelOptions(
            name='mailscannerreport',
            options={'verbose_name': 'mailscanner report', 'verbose_name_plural': 'mailscanner reports'},
        ),
        migrations.AlterModelOptions(
            name='mcpreport',
            options={'verbose_name': 'MCP report', 'verbose_name_plural': 'MCP reports'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='rblreport',
            options={'verbose_name': 'RBL report', 'verbose_name_plural': 'RBL reports'},
        ),
        migrations.CreateModel(
            name='SmtpRelay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(db_index=True, max_length=255, verbose_name='IP Address')),
                ('comment', models.TextField()),
                ('active', models.BooleanField(default=0)),
                ('hostname', models.CharField(db_index=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'smtp relay',
                'verbose_name_plural': 'smtp relays',
            },
        ),
        migrations.AlterModelOptions(
            name='spamreport',
            options={'verbose_name': 'spam report', 'verbose_name_plural': 'spam reports'},
        ),
        migrations.AlterModelOptions(
            name='transportlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('timestamp',), 'verbose_name': 'transport log entry', 'verbose_name_plural': 'transport log entries'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_ad_2d4929_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_addr_11d06f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_do_e2e93e_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_doma_1647b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_client__0c4c11_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_mailsca_75aba8_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='quarantined',
        ),
        migrations.AddField(
            model_name='message',
            name='stored',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stored'),
        ),
        migrations.AlterField(
            model_name='message',
            name='blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Blacklisted'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='infected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Infected'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_mcp',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is MCP'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_rbl_listed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Listed in RBL'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Spam'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailscanner_hostname',
            field=models.CharField(db_index=True, max_length=255, verbose_name='MailScanner Host'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mcp_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='MCP Score'),
        ),
        migrations.AlterField(
            model_name='message',
            name='released',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Released'),
        ),
        migrations.AlterField(
            model_name='message',
            name='size',
            field=models.FloatField(default=0, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='message',
            name='spam_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Spam Score'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='To domain'),
        ),
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.CharField(max_length=255, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='message',
            name='whitelisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Whitelisted'),
        ),
        migrations.AlterField(
            model_name='smtprelay',
            name='active',
            field=models.BooleanField(default=0, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='smtprelay',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='smtprelay',
            name='hostname',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='delay',
            field=models.DurationField(verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='dsn',
            field=models.CharField(db_index=True, max_length=255, verbose_name='DSN'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='dsn_message',
            field=models.TextField(db_index=True, verbose_name='DSN Message'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='relay_host',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Relayed to'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='transport_host',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Transported by'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='transport_type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Transportation Type'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'stored'], name='mail_messag_from_ad_7548b7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'stored'], name='mail_messag_to_addr_4c0f15_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'stored'], name='mail_messag_from_do_bb636c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'stored'], name='mail_messag_to_doma_2f0d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'stored'], name='mail_messag_client__bdb370_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'stored'], name='mail_messag_mailsca_aa6883_idx'),
        ),
        migrations.AlterModelOptions(
            name='smtprelay',
            options={'ordering': ('ip_address', 'hostname'), 'verbose_name': 'smtp relay', 'verbose_name_plural': 'smtp relays'},
        ),
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_domain',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_address',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_domain',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='To domain'),
        ),
        migrations.AddField(
            model_name='message',
            name='scanned',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Message has been scanned'),
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_ad_676957_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_ad_238390_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_addr_eec52d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_addr_0f2921_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_do_bf466c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_do_be122b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_doma_48b624_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_doma_da63ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_client__31eae6_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_client__9d8977_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_mailsca_eec5db_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_mailsca_e7750e_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='blacklisted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='whitelisted',
        ),
        migrations.AddField(
            model_name='message',
            name='allowed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Allowed'),
        ),
        migrations.AddField(
            model_name='message',
            name='blocked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Blocked'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'blocked'], name='mail_messag_from_ad_442bae_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'allowed'], name='mail_messag_from_ad_6e1ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'blocked'], name='mail_messag_to_addr_137362_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'allowed'], name='mail_messag_to_addr_095014_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'blocked'], name='mail_messag_from_do_1ecc68_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'allowed'], name='mail_messag_from_do_4bbc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'blocked'], name='mail_messag_to_doma_37c08d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'allowed'], name='mail_messag_to_doma_22c646_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'blocked'], name='mail_messag_client__60062a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'allowed'], name='mail_messag_client__5f85cc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'blocked'], name='mail_messag_mailsca_dbac4c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'allowed'], name='mail_messag_mailsca_765632_idx'),
        ),
    ]
