# Generated by Django 2.0 on 2017-12-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageHeaders',
            new_name='Headers',
        ),
    ]
