# Generated by Django 2.0.7 on 2018-07-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpamAssassinRule',
            new_name='SpamAssassinRuleDescription',
        ),
    ]
