# Generated by Django 2.0.7 on 2018-07-16 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_delete_spamassassinruledescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpRelay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('comment', models.TextField()),
            ],
        ),
    ]
