# Generated by Django 2.0 on 2018-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20180101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.CharField(max_length=255, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_domain',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_address',
            field=models.CharField(max_length=255, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_domain',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
