# Generated by Django 2.0 on 2018-01-01 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20180101_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailscannerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.TextField(blank=True, null=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
        migrations.AlterField(
            model_name='headers',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpreport',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rblreport',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
