# Generated by Django 2.0 on 2018-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20180101_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
