# Generated by Django 2.0 on 2018-01-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20180101_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headers',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='mailscannerreport',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='mcpreport',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='rblreport',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message'),
        ),
    ]
