# Generated by Django 2.0.7 on 2018-07-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_smtprelay_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtprelay',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=255, verbose_name='IP Address'),
        ),
    ]
