# Generated by Django 2.1.2 on 2018-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_auto_20180716_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headers',
            options={'verbose_name': 'headers', 'verbose_name_plural': 'headers'},
        ),
        migrations.AlterModelOptions(
            name='mailscannerreport',
            options={'verbose_name': 'mailscanner report', 'verbose_name_plural': 'mailscanner reports'},
        ),
        migrations.AlterModelOptions(
            name='mcpreport',
            options={'verbose_name': 'MCP report', 'verbose_name_plural': 'MCP reports'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='rblreport',
            options={'verbose_name': 'RBL report', 'verbose_name_plural': 'RBL reports'},
        ),
        migrations.AlterModelOptions(
            name='smtprelay',
            options={'verbose_name': 'smtp relay', 'verbose_name_plural': 'smtp relays'},
        ),
        migrations.AlterModelOptions(
            name='spamreport',
            options={'verbose_name': 'spam report', 'verbose_name_plural': 'spam reports'},
        ),
        migrations.AlterModelOptions(
            name='transportlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('timestamp',), 'verbose_name': 'transport log entry', 'verbose_name_plural': 'transport log entries'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_ad_2d4929_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_addr_11d06f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_do_e2e93e_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_doma_1647b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_client__0c4c11_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_mailsca_75aba8_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='quarantined',
        ),
        migrations.AddField(
            model_name='message',
            name='stored',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stored'),
        ),
        migrations.AlterField(
            model_name='message',
            name='blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Blacklisted'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='infected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Infected'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_mcp',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is MCP'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_rbl_listed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Listed in RBL'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Spam'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailscanner_hostname',
            field=models.CharField(db_index=True, max_length=255, verbose_name='MailScanner Host'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mcp_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='MCP Score'),
        ),
        migrations.AlterField(
            model_name='message',
            name='released',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Released'),
        ),
        migrations.AlterField(
            model_name='message',
            name='size',
            field=models.FloatField(default=0, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='message',
            name='spam_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Spam Score'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='To domain'),
        ),
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.CharField(max_length=255, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='message',
            name='whitelisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Whitelisted'),
        ),
        migrations.AlterField(
            model_name='smtprelay',
            name='active',
            field=models.BooleanField(default=0, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='smtprelay',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='smtprelay',
            name='hostname',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='delay',
            field=models.DurationField(verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='dsn',
            field=models.CharField(db_index=True, max_length=255, verbose_name='DSN'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='dsn_message',
            field=models.TextField(db_index=True, verbose_name='DSN Message'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='relay_host',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Relayed to'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='transport_host',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Transported by'),
        ),
        migrations.AlterField(
            model_name='transportlog',
            name='transport_type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Transportation Type'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'stored'], name='mail_messag_from_ad_7548b7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'stored'], name='mail_messag_to_addr_4c0f15_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'stored'], name='mail_messag_from_do_bb636c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'stored'], name='mail_messag_to_doma_2f0d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'stored'], name='mail_messag_client__bdb370_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'stored'], name='mail_messag_mailsca_aa6883_idx'),
        ),
    ]
