# Generated by Django 2.1.3 on 2018-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20181106_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_domain',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_address',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_domain',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='To domain'),
        ),
    ]
