# Generated by Django 2.1.3 on 2018-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_auto_20181227_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scanned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Message has been scanned'),
        ),
    ]
