# Generated by Django 2.1.4 on 2019-01-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_message_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='scanned',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Message has been scanned'),
        ),
    ]
