# Generated by Django 2.0 on 2018-01-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_auto_20180109_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headers',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='mailscannerreport',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='mcpreport',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='rblreport',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='spamreport',
            old_name='message_id',
            new_name='message',
        ),
    ]
