# Generated by Django 2.0 on 2018-01-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_auto_20180109_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailq_id',
            field=models.TextField(null=True, verbose_name='Mailqueue identification'),
        ),
        migrations.AlterField(
            model_name='message',
            name='spam_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
