# Generated by Django 3.1 on 2020-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_auto_20190102_1758'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_ad_676957_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_ad_238390_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_addr_eec52d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_addr_0f2921_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_do_bf466c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_from_do_be122b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_doma_48b624_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_to_doma_da63ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_client__31eae6_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_client__9d8977_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_mailsca_eec5db_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mail_messag_mailsca_e7750e_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='blacklisted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='whitelisted',
        ),
        migrations.AddField(
            model_name='message',
            name='allowed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Allowed'),
        ),
        migrations.AddField(
            model_name='message',
            name='blocked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Blocked'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'blocked'], name='mail_messag_from_ad_442bae_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_address', 'allowed'], name='mail_messag_from_ad_6e1ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'blocked'], name='mail_messag_to_addr_137362_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_address', 'allowed'], name='mail_messag_to_addr_095014_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'blocked'], name='mail_messag_from_do_1ecc68_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_domain', 'allowed'], name='mail_messag_from_do_4bbc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'blocked'], name='mail_messag_to_doma_37c08d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['to_domain', 'allowed'], name='mail_messag_to_doma_22c646_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'blocked'], name='mail_messag_client__60062a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_ip', 'allowed'], name='mail_messag_client__5f85cc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'blocked'], name='mail_messag_mailsca_dbac4c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailscanner_hostname', 'allowed'], name='mail_messag_mailsca_765632_idx'),
        ),
    ]
