# Generated by Django 2.0 on 2018-01-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_auto_20180109_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
