# Generated by Django 2.0 on 2018-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_auto_20180109_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
