# Generated by Django 2.0 on 2018-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_auto_20180110_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_address',
            field=models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='To'),
        ),
    ]
