# Generated by Django 2.0 on 2018-01-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0018_auto_20180111_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
    ]
