# Generated by Django 2.0.4 on 2018-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0020_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='blacklisted',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='infected',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_mcp',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_rbl_listed',
            field=models.NullBooleanField(db_index=True, default=False, verbose_name='Is RBL listed'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_spam',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mcp_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='quarantined',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='released',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='whitelisted',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
    ]
