# Generated by Django 2.0.4 on 2018-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0021_auto_20180407_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='blacklisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='infected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_mcp',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_rbl_listed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is RBL listed'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='quarantined',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='released',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='whitelisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
