# Generated by Django 2.0.4 on 2018-05-05 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0022_auto_20180410_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamAssassinRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
