# Generated by Django 2.0.5 on 2018-05-11 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0023_spamassassinrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_host', models.CharField(db_index=True, max_length=255)),
                ('transport_type', models.CharField(db_index=True, max_length=255)),
                ('relay_host', models.CharField(db_index=True, max_length=255)),
                ('dsn', models.CharField(db_index=True, max_length=255)),
                ('dsn_message', models.TextField(db_index=True)),
                ('delay', models.DurationField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
    ]
