# Generated by Django 2.0.5 on 2018-05-12 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0025_auto_20180512_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='transportlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
