# Generated by Django 2.0.5 on 2018-05-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0026_auto_20180512_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('timestamp',)},
        ),
    ]
