# Generated by Django 2.0.7 on 2018-07-09 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spamassassin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
