# Generated by Django 2.0.7 on 2018-07-09 16:04

from django.db import migrations

def create_sa_rules_0003(apps, schema_editor):
    Rule = apps.get_model('spamassassin', 'Rule')
    Rule.objects.update_or_create(name='SPF_NONE', defaults={'name': 'SPF_NONE', 'score':0.00})
    Rule.objects.update_or_create(name='SPF_HELO_NONE', defaults={'name': 'SPF_HELO_NONE', 'score': 0.00})
    Rule.objects.update_or_create(name='SPF_PASS', defaults={'name': 'SPF_PASS', 'score': -0.01})
    Rule.objects.update_or_create(name='SPF_HELO_PASS', defaults={'name': 'SPF_HELO_PASS', 'score': -0.001})
    Rule.objects.update_or_create(name='SPF_FAIL', defaults={'name': 'SPF_FAIL', 'score': 4.00})
    Rule.objects.update_or_create(name='SPF_HELO_FAIL', defaults={'name': 'SPF_HELO_FAIL', 'score': 4.00})
    Rule.objects.update_or_create(name='SPF_HELO_NEUTRAL', defaults={'name': 'SPF_HELO_NEUTRAL', 'score': 0.00})
    Rule.objects.update_or_create(name='SPF_HELO_SOFTFAIL', defaults={'name': 'SPF_HELO_SOFTFAIL', 'score': 1.50})
    Rule.objects.update_or_create(name='SPF_NEUTRAL', defaults={'name': 'SPF_NEUTRAL', 'score': 0.00})
    Rule.objects.update_or_create(name='SPF_SOFTFAIL', defaults={'name': 'SPF_SOFTFAIL', 'score': 1.50})
    Rule.objects.update_or_create(name='URIBL_AB_SURBL', defaults={'name': 'URIBL_AB_SURBL', 'score': 4.50})
    Rule.objects.update_or_create(name='URIBL_JP_SURBL', defaults={'name': 'URIBL_JP_SURBL', 'score': 1.90})
    Rule.objects.update_or_create(name='URIBL_WS_SURBL', defaults={'name': 'URIBL_WS_SURBL', 'score': 1.70})
    Rule.objects.update_or_create(name='URIBL_MW_SURBL', defaults={'name': 'URIBL_MW_SURBL', 'score': 1.30})
    Rule.objects.update_or_create(name='MISSING_MID', defaults={'name': 'MISSING_MID', 'score': 1.60})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_HTTP', defaults={'name': 'RCVD_IN_SORBS_HTTP', 'score': 0.00})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_SOCKS', defaults={'name': 'RCVD_IN_SORBS_SOCKS', 'score': 0.00})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_MISC', defaults={'name': 'RCVD_IN_SORBS_MISC', 'score': 2.60})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_SMTP', defaults={'name': 'RCVD_IN_SORBS_SMTP', 'score': 2.60})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_WEB', defaults={'name': 'RCVD_IN_SORBS_WEB', 'score': 0.00})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_BLOCK', defaults={'name': 'RCVD_IN_SORBS_BLOCK', 'score': 0.00})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_ZOMBIE', defaults={'name': 'RCVD_IN_SORBS_ZOMBIE', 'score': 1.00})
    Rule.objects.update_or_create(name='RCVD_IN_SORBS_DUL', defaults={'name': 'RCVD_IN_SORBS_DUL', 'score': 4.00})
    Rule.objects.update_or_create(name='RCVD_IN_XBL', defaults={'name': 'RCVD_IN_XBL', 'score': 4.73})
    Rule.objects.update_or_create(name='RCVD_IN_CBL', defaults={'name': 'RCVD_IN_CBL', 'score': 4.73})
    Rule.objects.update_or_create(name='RCVD_IN_PSBL', defaults={'name': 'RCVD_IN_PSBL', 'score': 2.70})
    Rule.objects.update_or_create(name='RCVD_IN_BRBL_LASTEXT', defaults={'name': 'RCVD_IN_BRBL_LASTEXT', 'score': 4.64})
    Rule.objects.update_or_create(name='URIBL_DBL_SPAM', defaults={'name': 'URIBL_DBL_SPAM', 'score': 2.70})
    Rule.objects.update_or_create(name='RCVD_IN_MSPIKE_L2', defaults={'name': 'RCVD_IN_MSPIKE_L2', 'score': 1.01})
    Rule.objects.update_or_create(name='RCVD_IN_MSPIKE_L3', defaults={'name': 'RCVD_IN_MSPIKE_L3', 'score': 2.49})
    Rule.objects.update_or_create(name='RCVD_IN_MSPIKE_L4', defaults={'name': 'RCVD_IN_MSPIKE_L4', 'score': 4.49})
    Rule.objects.update_or_create(name='RCVD_IN_MSPIKE_L5', defaults={'name': 'RCVD_IN_MSPIKE_L5', 'score': 6.19})
    Rule.objects.update_or_create(name='RDNS_DYNAMIC', defaults={'name': 'RDNS_DYNAMIC', 'score': 2.60})
    Rule.objects.update_or_create(name='RDNS_LOCALHOST', defaults={'name': 'RDNS_LOCALHOST', 'score': 1.00})
    Rule.objects.update_or_create(name='RDNS_NONE', defaults={'name': 'RDNS_NONE', 'score': 2.00})
    Rule.objects.update_or_create(name='BAYES_80', defaults={'name': 'BAYES_80', 'score': 4.20})
    Rule.objects.update_or_create(name='BAYES_99', defaults={'name': 'BAYES_99', 'score': 5.00})
    Rule.objects.update_or_create(name='BAYES_999', defaults={'name': 'BAYES_999', 'score': 1.00})
    Rule.objects.update_or_create(name='PYZOR_CHECK', defaults={'name': 'PYZOR_CHECK', 'score': 1.50})

class Migration(migrations.Migration):

    dependencies = [
        ('spamassassin', '0002_rule'),
    ]

    operations = [
        migrations.RunPython(create_sa_rules_0003)
    ]
