# Generated by Django 2.0.7 on 2018-07-13 22:24

from django.db import migrations

def create_sa_rules_0004(apps, schema_editor):
    Rule = apps.get_model('spamassassin', 'Rule')
    Rule.objects.update_or_create(name='BAYES_50', defaults={'name': 'BAYES_50', 'score':1.50})
    Rule.objects.update_or_create(name='MIME_HTML_ONLY', defaults={'name': 'MIME_HTML_ONLY', 'score':0.72})
    Rule.objects.update_or_create(name='HTML_MIME_NO_HTML_TAG', defaults={'name': 'HTML_MIME_NO_HTML_TAG', 'score':0.38})
    Rule.objects.update_or_create(name='TO_EQ_FM_DOM_SPF_FAIL', defaults={'name': 'TO_EQ_FM_DOM_SPF_FAIL', 'score':0.23})
    Rule.objects.update_or_create(name='RAZOR2_CF_RANGE_51_100', defaults={'name': 'RAZOR2_CF_RANGE_51_100', 'score':2.00})
    Rule.objects.update_or_create(name='RAZOR2_CHECK', defaults={'name': 'RAZOR2_CHECK', 'score':0.90})
    Rule.objects.update_or_create(name='MAILING_LIST_MULTI', defaults={'name': 'MAILING_LIST_MULTI', 'score':-1.00})
    Rule.objects.update_or_create(name='MPART_ALT_DIFF', defaults={'name': 'MPART_ALT_DIFF', 'score':0.80})
    Rule.objects.update_or_create(name='HTML_IMAGE_RATIO_02', defaults={'name': 'HTML_IMAGE_RATIO_02', 'score':0.44})
    Rule.objects.update_or_create(name='FROM_EXCESS_BASE64', defaults={'name': 'FROM_EXCESS_BASE64', 'score':0.98})
    Rule.objects.update_or_create(name='HTML_IMAGE_RATIO_04', defaults={'name': 'HTML_IMAGE_RATIO_04', 'score':0.56})
    Rule.objects.update_or_create(name='USER_IN_DEF_SPF_WL', defaults={'name': 'USER_IN_DEF_SPF_WL', 'score':-5.00})
    Rule.objects.update_or_create(name='USER_IN_DEF_DKIM_WL', defaults={'name': 'USER_IN_DEF_DKIM_WL', 'score':-5.00})
    Rule.objects.update_or_create(name='HTML_IMAGE_ONLY_24', defaults={'name': 'HTML_IMAGE_ONLY_24', 'score':1.62})
    Rule.objects.update_or_create(name='BAYES_60', defaults={'name': 'BAYES_60', 'score':2.00})
    Rule.objects.update_or_create(name='SUBJ_ALL_CAPS', defaults={'name': 'SUBJ_ALL_CAPS', 'score':1.00})
    Rule.objects.update_or_create(name='URI_HEX', defaults={'name': 'URI_HEX', 'score':1.00})

class Migration(migrations.Migration):

    dependencies = [
        ('spamassassin', '0003_auto_20180709_1604'),
    ]

    operations = [
        migrations.RunPython(create_sa_rules_0004)
    ]
