# Generated by Django 2.1.2 on 2018-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamassassin', '0004_auto_20180713_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'rule', 'verbose_name_plural': 'rules'},
        ),
        migrations.AlterModelOptions(
            name='ruledescription',
            options={'verbose_name': 'rule description', 'verbose_name_plural': 'rule descriptions'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='ruledescription',
            name='key',
            field=models.CharField(max_length=255, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='ruledescription',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
