# Generated by Django 2.1.3 on 2018-11-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamassassin', '0005_auto_20181023_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruledescription',
            options={'ordering': ('key',), 'verbose_name': 'rule description', 'verbose_name_plural': 'rule descriptions'},
        ),
    ]
