# Generated by Django 2.1.3 on 2018-11-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamassassin', '0006_auto_20181106_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('name',), 'verbose_name': 'rule', 'verbose_name_plural': 'rules'},
        ),
    ]
