from mailguardian.app.service_providers.service_container import ServiceContainer, setup_service_container
from mailguardian.app.service_providers.dependency_injection import inject_dependencies, Depends
