# Generated by Django 3.2.4 on 2021-07-13 18:32

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    replaces = [('lists', '0001_initial'), ('lists', '0002_auto_20180518_2151'), ('lists', '0003_auto_20180521_0213'), ('lists', '0004_remove_listentry_from_domain'), ('lists', '0005_auto_20180521_0222'), ('lists', '0006_auto_20181023_1931'), ('lists', '0007_auto_20181106_1913'), ('lists', '0008_auto_20190102_1815'), ('lists', '0009_listentry_from_domain'), ('lists', '0010_auto_20200808_1930'), ('lists', '0011_auto_20200808_2035')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='From')),
                ('to_address', models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='To')),
                ('listing_type', models.CharField(choices=[('blacklisted', 'Blacklisted'), ('whitelisted', 'Whitelisted')], db_index=True, max_length=12)),
            ],
            options={
                'db_table': 'list_entries',
            },
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'to_address'], name='list_entrie_from_ad_764895_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'listing_type'], name='list_entrie_from_ad_602555_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'listing_type'], name='list_entrie_to_addr_890969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'to_address', 'listing_type')},
        ),
        migrations.AddField(
            model_name='listentry',
            name='to_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='To'),
        ),
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'to_address', 'to_domain', 'listing_type')},
        ),
        migrations.AlterModelOptions(
            name='listentry',
            options={'verbose_name': 'listing entry', 'verbose_name_plural': 'listing entries'},
        ),
        migrations.AlterField(
            model_name='listentry',
            name='listing_type',
            field=models.CharField(choices=[('blacklisted', 'Blacklisted'), ('whitelisted', 'Whitelisted')], db_index=True, max_length=12, verbose_name='Listing type'),
        ),
        migrations.AlterModelOptions(
            name='listentry',
            options={'ordering': ('listing_type', 'from_address', 'to_address'), 'verbose_name': 'listing entry', 'verbose_name_plural': 'listing entries'},
        ),
        migrations.AlterField(
            model_name='listentry',
            name='from_address',
            field=models.CharField(db_index=True, default='', max_length=511, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='to_address',
            field=models.CharField(db_index=True, default='', max_length=511, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='listentry',
            name='from_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='listing_type',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('allowed', 'Allowed')], db_index=True, max_length=12, verbose_name='Listing type'),
        ),
    ]
