# Generated by Django 2.0.5 on 2018-05-15 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='From')),
                ('to_address', models.CharField(blank=True, db_index=True, default='', max_length=511, verbose_name='To')),
                ('listing_type', models.CharField(choices=[('blacklisted', 'Blacklisted'), ('whitelisted', 'Whitelisted')], db_index=True, max_length=12)),
            ],
            options={
                'db_table': 'list_entries',
            },
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'to_address'], name='list_entrie_from_ad_764895_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'listing_type'], name='list_entrie_from_ad_602555_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'listing_type'], name='list_entrie_to_addr_890969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'to_address', 'listing_type')},
        ),
    ]
