# Generated by Django 2.0 on 2018-01-09 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_address', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='From')),
                ('to_address', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='To')),
                ('from_domain', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('to_domain', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('from_ip_address', models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='IP Address')),
                ('to_ip_address', models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='IP Address')),
                ('listing_type', models.CharField(choices=[('blacklisted', 'Blacklisted'), ('whitelisted', 'Whitelisted')], db_index=True, max_length=12)),
            ],
            options={
                'db_table': 'lists',
            },
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'from_domain'], name='lists_from_ad_05a75c_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'to_domain'], name='lists_to_addr_90af20_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'to_address'], name='lists_from_ad_32a47e_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'to_domain'], name='lists_from_ad_af9964_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'from_domain'], name='lists_to_addr_7fee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['listing_type', 'from_domain'], name='lists_listing_21caf2_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'listing_type'], name='lists_from_ad_6bf89b_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['listing_type', 'to_domain'], name='lists_listing_c37bff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'from_domain', 'to_address', 'to_domain', 'from_ip_address', 'to_ip_address', 'listing_type')},
        ),
    ]
