# Generated by Django 2.0 on 2018-01-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_from_ad_05a75c_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_to_addr_90af20_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_from_ad_32a47e_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_from_ad_af9964_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_to_addr_7fee6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_listing_21caf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_from_ad_6bf89b_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='lists_listing_c37bff_idx',
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'from_domain'], name='list_entrie_from_ad_30052a_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'to_domain'], name='list_entrie_to_addr_53da7e_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'to_address'], name='list_entrie_from_ad_764895_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'to_domain'], name='list_entrie_from_ad_fbfadb_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'from_domain'], name='list_entrie_to_addr_93281d_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['listing_type', 'from_domain'], name='list_entrie_listing_3572d5_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['from_address', 'listing_type'], name='list_entrie_from_ad_602555_idx'),
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['listing_type', 'to_domain'], name='list_entrie_listing_219b6b_idx'),
        ),
        migrations.AlterModelTable(
            name='listentry',
            table='list_entries',
        ),
    ]
