# Generated by Django 2.0.5 on 2018-05-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180518_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='from_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='to_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='To'),
        ),
    ]
