# Generated by Django 2.0 on 2018-01-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180110_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'from_domain', 'to_address', 'to_domain', 'from_ip_address', 'to_ip_address')},
        ),
    ]
