# Generated by Django 2.0.5 on 2018-05-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180521_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listentry',
            name='from_domain',
        ),
    ]
