# Generated by Django 2.0.5 on 2018-05-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_listentry_from_domain'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'to_address', 'to_domain', 'listing_type')},
        ),
    ]
