# Generated by Django 2.0 on 2018-01-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20180112_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='from_ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='to_ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address'),
        ),
    ]
