# Generated by Django 2.1.2 on 2018-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180521_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listentry',
            options={'verbose_name': 'listing entry', 'verbose_name_plural': 'listing entries'},
        ),
        migrations.AlterField(
            model_name='listentry',
            name='listing_type',
            field=models.CharField(choices=[('blacklisted', 'Blacklisted'), ('whitelisted', 'Whitelisted')], db_index=True, max_length=12, verbose_name='Listing type'),
        ),
    ]
