# Generated by Django 2.0.4 on 2018-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180119_1521'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listentry',
            name='list_entrie_from_ad_30052a_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='list_entrie_to_addr_53da7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='list_entrie_from_ad_fbfadb_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='list_entrie_to_addr_93281d_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='list_entrie_listing_3572d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='listentry',
            name='list_entrie_listing_219b6b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='listentry',
            unique_together={('from_address', 'to_address', 'listing_type')},
        ),
        migrations.AddIndex(
            model_name='listentry',
            index=models.Index(fields=['to_address', 'listing_type'], name='list_entrie_to_addr_890969_idx'),
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='from_domain',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='from_ip_address',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='to_domain',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='to_ip_address',
        ),
    ]
