# Generated by Django 2.1.3 on 2018-11-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20181023_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listentry',
            options={'ordering': ('listing_type', 'from_address', 'to_address'), 'verbose_name': 'listing entry', 'verbose_name_plural': 'listing entries'},
        ),
    ]
