# Generated by Django 2.1.4 on 2019-01-02 18:24

from django.db import migrations, models

def fix_domains_migrations_0009(apps, schema_editor):
    ListEntry = apps.get_model('lists', 'ListEntry')
    for entry in ListEntry.objects.all():
        entry.from_domain = entry.from_address.split('@')[-1]
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20190102_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='from_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='From'),
        ),
        migrations.RunPython(fix_domains_migrations_0009),
    ]
