# Generated by Django 3.1 on 2020-08-08 18:35

from django.db import migrations

def change_allowed_and_blocked_0011(apps, schema_editor):
    ListEntry = apps.get_model('lists', 'ListEntry')
    for entry in ListEntry.objects.all():
        if entry.listing_type == 'blacklisted':
            entry.listing_type = 'blocked'
            entry.save()
        elif entry.listing_type == 'whitelisted':
            entry.listing_type = 'allowed'
            entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20200808_1930'),
    ]

    operations = [
        migrations.RunPython(change_allowed_and_blocked_0011)
    ]
