"""empty message

Revision ID: 03252ae5a5c4
Revises: 2602d3e5a0d4
Create Date: 2025-01-10 21:39:42.487964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '03252ae5a5c4'
down_revision: Union[str, None] = '2602d3e5a0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    op.create_index(op.f('ix_recovery_codes_uuid'), 'recovery_codes', ['uuid'], unique=False)
    op.create_table('totp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_totp_codes_user_id'), 'totp_codes', ['user_id'], unique=False)
    op.create_index(op.f('ix_totp_codes_uuid'), 'totp_codes', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_totp_codes_uuid'), table_name='totp_codes')
    op.drop_index(op.f('ix_totp_codes_user_id'), table_name='totp_codes')
    op.drop_table('totp_codes')
    op.drop_index(op.f('ix_recovery_codes_uuid'), table_name='recovery_codes')
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    # ### end Alembic commands ###
