"""empty message

Revision ID: 2bf9f458e158
Revises: ea5e7446b609
Create Date: 2024-08-22 21:28:43.497313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2bf9f458e158'
down_revision: Union[str, None] = 'ea5e7446b609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_transport_log_ids',
    sa.Column('smtpd_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('smtp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('smtpd_id', 'smtp_id')
    )
    op.add_column('message_transport_log', sa.Column('mail_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('messages', sa.Column('mail_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'mail_message_id')
    op.drop_column('message_transport_log', 'mail_message_id')
    op.drop_table('message_transport_log_ids')
    # ### end Alembic commands ###
