"""empty message

Revision ID: 902e96660a66
Revises: b7c863147153
Create Date: 2024-09-17 21:20:23.617939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '902e96660a66'
down_revision: Union[str, None] = 'b7c863147153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('acted_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('changes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_uuid'), 'audit_log', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_uuid'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
