"""empty message

Revision ID: a8b097d39c26
Revises: e76fde041698
Create Date: 2025-01-17 21:16:10.556368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a8b097d39c26'
down_revision: Union[str, None] = 'e76fde041698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('totp_codes', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('totp_codes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('totp_codes', 'created_at')
    op.drop_column('totp_codes', 'name')
    # ### end Alembic commands ###
