"""empty message

Revision ID: b7c863147153
Revises: 2bf9f458e158
Create Date: 2024-09-12 20:40:25.165390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b7c863147153'
down_revision: Union[str, None] = '2bf9f458e158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RECEIVED', 'STARTED', 'SUCCESS', 'FAILURE', 'REVOKED', 'REJECTED', 'RETRY', 'IGNORED', name='taskstate'), nullable=False),
    sa.Column('node_uuid', sa.Uuid(), nullable=True),
    sa.Column('queue_uuid', sa.Uuid(), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_module'), 'tasks', ['module'], unique=False)
    op.create_index(op.f('ix_tasks_node_uuid'), 'tasks', ['node_uuid'], unique=False)
    op.create_index(op.f('ix_tasks_queue_uuid'), 'tasks', ['queue_uuid'], unique=False)
    op.create_index(op.f('ix_tasks_task'), 'tasks', ['task'], unique=False)
    op.create_index(op.f('ix_tasks_uuid'), 'tasks', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_uuid'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_queue_uuid'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_node_uuid'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_module'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
