"""empty message

Revision ID: cbae91cca8a0
Revises: fe8dee784f76
Create Date: 2025-05-20 20:34:10.290357

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbae91cca8a0'
down_revision: str | None = 'fe8dee784f76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('designate_as_spam', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('designate_as_definite_spam', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('bypass_spam_check', sa.Boolean(), server_default=sa.sql.false(), nullable=False))
    op.add_column('users', sa.Column('designate_as_spam', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('designate_as_definite_spam', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bypass_spam_check', sa.Boolean(), server_default=sa.sql.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bypass_spam_check')
    op.drop_column('users', 'designate_as_definite_spam')
    op.drop_column('users', 'designate_as_spam')
    op.drop_column('domains', 'bypass_spam_check')
    op.drop_column('domains', 'designate_as_definite_spam')
    op.drop_column('domains', 'designate_as_spam')
    # ### end Alembic commands ###
