"""empty message

Revision ID: ea5e7446b609
Revises: 5484b266d10b
Create Date: 2024-04-28 11:42:36.638338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ea5e7446b609'
down_revision: Union[str, None] = '5484b266d10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_mailscanner_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('contents', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_mailscanner_reports_message_id'), 'message_mailscanner_reports', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_mailscanner_reports_uuid'), 'message_mailscanner_reports', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_mailscanner_reports_uuid'), table_name='message_mailscanner_reports')
    op.drop_index(op.f('ix_message_mailscanner_reports_message_id'), table_name='message_mailscanner_reports')
    op.drop_table('message_mailscanner_reports')
    # ### end Alembic commands ###
