# Generated by Django 2.0.2 on 2018-02-21 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailScannerConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='mailscannerconfiguration',
            index=models.Index(fields=['key'], name='core_mailsc_key_782e5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailscannerconfiguration',
            unique_together={('key', 'value')},
        ),
    ]
