# Generated by Django 4.1.1 on 2022-09-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_v2_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtask',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='applicationtask',
            name='host',
        ),
        migrations.RemoveField(
            model_name='applicationtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='MailScannerConfiguration',
        ),
        migrations.DeleteModel(
            name='SpamAssassinConfiguration',
        ),
        migrations.RemoveField(
            model_name='twofactorbackupcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactorconfiguration',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicationTask',
        ),
        migrations.DeleteModel(
            name='TwoFactorBackupCode',
        ),
        migrations.DeleteModel(
            name='TwoFactorConfiguration',
        ),
    ]
