# Generated by Django 2.0.3 on 2018-03-15 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180221_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpamAssassinConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('filepath', models.CharField(default='/etc/MailScanner/spamassassin.conf', max_length=511)),
            ],
        ),
        migrations.AddIndex(
            model_name='spamassassinconfiguration',
            index=models.Index(fields=['key'], name='core_spamas_key_d924cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spamassassinconfiguration',
            unique_together={('key', 'value')},
        ),
    ]
