# Generated by Django 2.0.5 on 2018-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180527_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_quarantine_report',
            field=models.BooleanField(default=False),
        ),
    ]
