# Generated by Django 2.0.3 on 2018-03-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180315_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.AlterModelTable(
            name='setting',
            table='core_settings',
        ),
    ]
