# Generated by Django 2.0.6 on 2018-06-06 23:14

from django.db import migrations

def update_create_settings_0005(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    # Create settings added to the database as part of the features introduced with this version
    Setting.objects.update_or_create(key='quarantine.report.days', defaults={'key' : 'quarantine.report.days', 'value' : '7'})
    Setting.objects.update_or_create(key='quarantine.report.unknown.hide', defaults={'key' : 'quarantine.report.unknown.hide', 'value' : '1'})
    Setting.objects.update_or_create(key='sa.last_updated', defaults={'key' : 'sa.last_updated', 'value' : ''})
    Setting.objects.update_or_create(key='quarantine.release.body', defaults={'key' : 'quarantine.release.body', 'value' : 'Please find the original message that was quarantined attached to this mail.Regards,Postmaster'})
    Setting.objects.update_or_create(key='quarantine.filters.combine', defaults={'key' : 'quarantine.filters.combine', 'value' : '1'})
    Setting.objects.update_or_create(key='mailscanner.configuration.edit', defaults={'key' : 'mailscanner.configuration.edit', 'value' : '0'})
    Setting.objects.update_or_create(key='mailscanner.rules.edit', defaults={'key' : 'mailscanner.rules.edit', 'value' : '0'})

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180528_2039'),
    ]

    operations = [
        migrations.RunPython(update_create_settings_0005)
    ]
