# Generated by Django 2.0.6 on 2018-06-22 13:17

from django.db import migrations

def update_create_settings_0006(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    # Create settings added to the database as part of the features introduced with this version
    Setting.objects.update_or_create(key='mail.spamassassin.score', defaults={'key' : 'mail.spamassassin.score', 'value' : '5'})
    Setting.objects.update_or_create(key='mail.spamassassin.highscore', defaults={'key' : 'mail.spamassassin.highscore', 'value' : '15'})

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180607_0114'),
    ]

    operations = [
        migrations.RunPython(update_create_settings_0006)
    ]
