# Generated by Django 2.0.6 on 2018-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180622_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_spam_highscore',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_spam_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='user',
            name='skip_scan',
            field=models.BooleanField(default=False),
        ),
    ]
