# Generated by Django 2.0.6 on 2018-06-27 17:43

from django.db import migrations
import platform

def update_create_settings_0008(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    # Create settings added to the database as part of the features introduced with this version
    Setting.objects.update_or_create(key='mail.release.sender', defaults={'key' : 'mail.release.sender', 'value' : 'postmaster@{0}'.format(platform.node())})

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180622_1523'),
    ]

    operations = [
        migrations.RunPython(update_create_settings_0008)
    ]
