# Generated by Django 2.0.6 on 2018-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mailscannerhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailscannerhost',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
    ]
