# Generated by Django 2.0.7 on 2018-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180704_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailscannerhost',
            name='priority',
            field=models.IntegerField(default=10, verbose_name='MX Priority'),
        ),
    ]
