# Generated by Django 2.0.7 on 2018-07-14 14:07

from django.db import migrations

def update_create_settings_0012(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    # Create settings added to the database as part of the features introduced with this version
    Setting.objects.filter(key='quarantine.report.days').delete()
    Setting.objects.update_or_create(key='quarantine.report.weekly', defaults={'key' : 'quarantine.report.weekly', 'value' : True})
    Setting.objects.update_or_create(key='quarantine.report.monthly', defaults={'key' : 'quarantine.report.monthly', 'value' : False})

    
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mailscannerhost_priority'),
    ]

    operations = [
        migrations.RunPython(update_create_settings_0012)
    ]
