# Generated by Django 2.1 on 2018-08-19 08:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_auto_20180714_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(null=True)),
                ('completed', models.DateTimeField(null=True)),
                ('status_code', models.CharField(blank=True, choices=[('QUEUED', 'queued'), ('RUNNING', 'running'), ('FAILED', 'failed'), ('COMPLETED', 'completed')], default='QUEUED', max_length=255)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('object_pk', models.CharField(db_index=True, max_length=255, verbose_name='object primary key')),
                ('method', models.CharField(max_length=255, verbose_name='method')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='parameters')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='content type')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MailScannerHost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
