# Generated by Django 2.1 on 2018-08-28 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_applicationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('notification_type', models.CharField(choices=[('dashboard', 'Dasboard'), ('login', 'Login')], max_length=20)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
