# Generated by Django 2.1 on 2018-08-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_applicationnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationnotification',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='date_start',
            field=models.DateField(),
        ),
    ]
