# Generated by Django 2.1.2 on 2018-10-18 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_twofactorconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='twofactorconfiguration',
            name='totp_key',
            field=models.CharField(),
        ),
    ]
