# Generated by Django 2.1.2 on 2018-10-23 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181018_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationnotification',
            options={'ordering': ('-id',), 'verbose_name': 'application notification', 'verbose_name_plural': 'application notifications'},
        ),
        migrations.AlterModelOptions(
            name='applicationtask',
            options={'verbose_name': 'application task', 'verbose_name_plural': 'application tasks'},
        ),
        migrations.AlterModelOptions(
            name='mailscannerconfiguration',
            options={'verbose_name': 'mailscanner configuration', 'verbose_name_plural': 'mailscanner configuration'},
        ),
        migrations.AlterModelOptions(
            name='mailscannerhost',
            options={'verbose_name': 'mailscanner host', 'verbose_name_plural': 'mailscanner hosts'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('key',), 'verbose_name': 'setting', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelOptions(
            name='spamassassinconfiguration',
            options={'verbose_name': 'SpamAssassin configuration', 'verbose_name_plural': 'SpamAssassin configuration'},
        ),
        migrations.AlterModelOptions(
            name='twofactorbackupcode',
            options={'verbose_name': 'two factor backup code', 'verbose_name_plural': 'two factor backup codes'},
        ),
        migrations.AlterModelOptions(
            name='twofactorconfiguration',
            options={'verbose_name': 'two factor configuration', 'verbose_name_plural': 'two factor configuration'},
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='date_end',
            field=models.DateField(verbose_name='Ending on'),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='date_start',
            field=models.DateField(verbose_name='Starting on'),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='notification_type',
            field=models.CharField(choices=[('dashboard', 'Dasboard'), ('login', 'Login')], max_length=20, verbose_name='Notification type'),
        ),
        migrations.AlterField(
            model_name='applicationnotification',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='completed',
            field=models.DateTimeField(null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MailScannerHost', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='status_code',
            field=models.CharField(blank=True, choices=[('QUEUED', 'queued'), ('RUNNING', 'running'), ('FAILED', 'failed'), ('COMPLETED', 'completed')], default='QUEUED', max_length=255, verbose_name='Status code'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='status_message',
            field=models.TextField(blank=True, null=True, verbose_name='Status message'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='updated',
            field=models.DateTimeField(null=True, verbose_name='Last updated on'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='mailscannerconfiguration',
            name='filepath',
            field=models.CharField(default='/etc/MailScanner/MailScanner.conf', max_length=511, verbose_name='Filepath'),
        ),
        migrations.AlterField(
            model_name='mailscannerconfiguration',
            name='key',
            field=models.CharField(max_length=255, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='mailscannerconfiguration',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='mailscannerhost',
            name='hostname',
            field=models.CharField(max_length=255, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='spamassassinconfiguration',
            name='filepath',
            field=models.CharField(default='/etc/MailScanner/spamassassin.conf', max_length=511, verbose_name='Filepath'),
        ),
        migrations.AlterField(
            model_name='spamassassinconfiguration',
            name='key',
            field=models.CharField(max_length=255, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='spamassassinconfiguration',
            name='rule',
            field=models.CharField(max_length=255, verbose_name='Rule'),
        ),
        migrations.AlterField(
            model_name='spamassassinconfiguration',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='code',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Two Factor Backup Code'),
        ),
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='twofactorconfiguration',
            name='totp_key',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Timebased Onetime Password Key'),
        ),
        migrations.AlterField(
            model_name='twofactorconfiguration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
