# Generated by Django 2.1.2 on 2018-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181023_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationnotification',
            name='notification_type',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('login', 'Login')], max_length=20, verbose_name='Notification type'),
        ),
    ]
