# Generated by Django 2.1.3 on 2018-11-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181106_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailscannerhost',
            options={'ordering': ('hostname', 'ip_address'), 'verbose_name': 'mailscanner host', 'verbose_name_plural': 'mailscanner hosts'},
        ),
    ]
