# Generated by Django 2.1.3 on 2018-11-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181106_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailscannerhost',
            name='passive',
            field=models.BooleanField(default=0, verbose_name='Passive host'),
        ),
    ]
