# Generated by Django 3.1 on 2020-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200807_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtask',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='parameters'),
        ),
    ]
